### ISSUE TITLE
The ecs Fargate services fails to come up, leading to the CFN role back

### ISSUE THREAD

**Issue by kartraj123** [aws-quickstart/quickstart-duo-mfa#43] opened 2021-07-13 17:06 UTC
The ecs Fargate services fails to start with the below error.

ResourceInitializationError: unable to pull secrets or registry auth: execution resource retrieval failed: unable to retrieve secret from asm: service call has been retried 5 time(s): failed to fetch secret arn:aws:secretsmanager:us-east-1:......

**Comment by davmayd** [comment] 2021-07-14 18:23
This looks like a either transient issue with Secrets Manager or an issue with your account not having appropriate permissions. I was unable to replicate in us-east-1 and successfully deployed the stack.

**Comment by agponte** [comment] 2021-07-15 05:30
It was definitely an issue on AWS side, after their research they told me it was resolved without giving any root cause.

**Closed** 2021-08-11 22:16 UTC
